"""Offline shared location reference. Regenerated by frontend/scripts/generate-geography.cjs."""
import json
from pathlib import Path

COUNTRIES = [
    {key: row[key] for key in ('code', 'name', 'flag')}
    for row in json.loads((Path(__file__).parent / 'data' / 'countries.json').read_text(encoding='utf-8'))
]

_ALIASES = {
    'US': ['USA', 'United States of America'], 'GB': ['UK'], 'AE': ['UAE'],
    'KR': ['Korea, Republic of'], 'RU': ['Russian Federation'], 'VN': ['Viet Nam'],
    'TR': ['Türkiye'], 'CZ': ['Czechia'], 'PS': ['Palestine, State of', 'Palestinian Territory Occupied'],
    'VA': ['Holy See', 'Vatican City State (Holy See)'],
}


def country_values(value: str) -> list[str]:
    """Match new full names without losing legacy event aliases or ISO values."""
    key = value.strip().casefold()
    for country in COUNTRIES:
        names = [country['code'], country['name'], *_ALIASES.get(country['code'], [])]
        if key in {name.casefold() for name in names}:
            return list(dict.fromkeys([value, *names]))
    return [value]